theme: jekyll-theme-cayman
lang: "es-ES"
title: "Mapa de la Opresión en Cuba"
description: "Aplicación para Android que pretende obtener información que el público debe conocer y que es de utilidad para los activistas de derechos humanos..."
show_downloads: "true"
